[HOTFIX] Fixing UI Implementation
uasoft-indonesia/badaso-lms-theme pull request #101
Opened 2022-06-09 23:38 UTC by FXDROS

Several things have been done:
1. Move the `logout` button to the bottom of the sidebar
2. Add a default avatar icon on course menu
3. Change avatar circle size to 48px and change the bg-color to secondary
4. Give background color on the announcement to differentiate it from the comments section.
5. Edit people in the course list
6. Edit layout for `create topic`

![Screen Shot 2022-06-10 at 06 29 05](https://user-images.githubusercontent.com/57487697/172962261-612b9eda-dfca-4d98-a30d-463133f9cac3.png)
![Screen Shot 2022-06-10 at 06 29 11](https://user-images.githubusercontent.com/57487697/172962271-555fe29a-f4f0-4834-9dcd-6427df7b4abb.png)
![Screen Shot 2022-06-10 at 06 29 17](https://user-images.githubusercontent.com/57487697/172962281-7092c863-28c0-4d4a-a615-965967be7abc.png)
![Screen Shot 2022-06-10 at 06 29 21](https://user-images.githubusercontent.com/57487697/172962285-8ecf60a7-4db1-4778-ad70-1da36d439339.png)
![Screen Shot 2022-06-10 at 06 35 50](https://user-images.githubusercontent.com/57487697/172962291-0b24dfc3-fec0-486a-9c0d-a83166de859b.png)

2022-06-10 10:41 UTC, AldiNFitrah reviewed
in the screenshots that you provided, the user avatar is still broken. Can we fix it?

2022-06-10 10:41 UTC, AldiNFitrah commented on src/resources/app/components/Container/AnnouncementContainer.vue
> +        console.log(this.announcements)
can it be removed?

2022-06-10 10:41 UTC, AldiNFitrah commented on src/resources/app/components/Sidebar.vue
>            <v-icon color="error">mdi-logout</v-icon>
these should be intended I guess

2022-06-10 10:41 UTC, AldiNFitrah commented on src/resources/app/pages/CreateTopic.vue
> +import CreationLayout from "../components/Layout/CreationLayout";
minor: reorder the imports please

2022-06-11 05:10 UTC, AldiNFitrah approved these changes

2022-06-11 05:33 UTC, IlmaMannix requested changes
thank uuuu bas ^^

2022-06-11 05:33 UTC, IlmaMannix approved these changes
thank u basss

2022-06-11 05:45 UTC, merged