[WIP] PBI 2 - User can login
uasoft-indonesia/badaso-lms-theme pull request #18
Opened 2022-03-09 15:59 UTC by nofamex

2022-03-11 10:20 UTC, Zsaschz commented on src/resources/app/pages/login.vue
> +            Login
you can use a loading icon while running the request for better user experience

2022-03-11 10:23 UTC, Zsaschz approved these changes
still got some todos, but i think this pr has covered the basic functionality and can be merged

2022-03-12 06:02 UTC, FXDROS approved these changes
everything seems pretty good

2022-03-12 06:03 UTC, IlmaMannix approved these changes

2022-03-12 06:08 UTC, AldiNFitrah requested changes

2022-03-12 06:08 UTC, AldiNFitrah commented on src/resources/api/auth.js
> +let apiPrefix = "/badaso-api/module/lms/v1/auth/";
please use const since this won't be changed

2022-03-12 06:08 UTC, AldiNFitrah commented on src/resources/api/auth.js
> +    let ep = apiPrefix + "register";
woops didn't notice this one before. `ep` is not clear enough IMO, please change it to something like `url`

2022-03-12 06:08 UTC, AldiNFitrah commented on src/resources/api/auth.js
> +  async login(data) {
whitespace please

2022-03-12 06:08 UTC, AldiNFitrah commented on src/resources/api/auth.js
> +    let ep = apiPrefix + "login";
same for this one, `ep` is not descriptive

2022-03-12 06:08 UTC, AldiNFitrah commented on src/resources/app/pages/login.vue
> +            @click="submit"
where is this `"submit"` referring to?

2022-03-12 06:42 UTC, nofamex commented on src/resources/app/pages/login.vue
> +            @click="submit"
submit function

2022-03-12 06:48 UTC, merged