PBI-16,17,18,19: Topic in class
uasoft-indonesia/badaso-lms-theme pull request #61
Opened 2022-04-04 23:11 UTC by darren-ngoh

2022-04-04 23:46 UTC, AldiNFitrah commented on src/resources/app/pages/Classwork.vue
> +        // },
please remove it if unused

2022-04-04 23:46 UTC, AldiNFitrah commented on src/resources/app/pages/CreateTopic.vue
> +      </v-row> -->
this one too

2022-04-04 23:46 UTC, AldiNFitrah commented on src/resources/app/pages/CreateTopic.vue
> +      // topicDesc: "",
and this

2022-04-04 23:46 UTC, AldiNFitrah commented on src/resources/app/pages/CreateTopic.vue
> +        // }
this one as well

2022-04-04 23:46 UTC, AldiNFitrah commented on src/resources/app/pages/UpdateTopic.vue
> +      </v-row> -->
uhuh

2022-04-04 23:46 UTC, AldiNFitrah commented on src/resources/app/pages/UpdateTopic.vue
> +      // topicDesc: "",
yap

2022-04-04 23:46 UTC, AldiNFitrah commented on src/resources/app/pages/UpdateTopic.vue
> +        // }
should be the last

2022-04-04 23:56 UTC, IlmaMannix requested changes

2022-04-04 23:56 UTC, IlmaMannix commented on src/resources/app/pages/Classwork.vue
> +        // {
Delete this comment

2022-04-04 23:56 UTC, IlmaMannix commented on src/resources/app/pages/CreateTopic.vue
> +      <!-- <v-row>
Delete this comment

2022-04-04 23:56 UTC, IlmaMannix commented on src/resources/app/pages/CreateTopic.vue
> +      // topicDesc: "",
Delete this comment

2022-04-04 23:56 UTC, IlmaMannix commented on src/resources/app/pages/CreateTopic.vue
> +        // if (error) {
Delete this comment

2022-04-04 23:56 UTC, IlmaMannix commented on src/resources/app/pages/UpdateTopic.vue
> +    this.getData(this.id);
(actually no prob 😑) this.$props.id

2022-04-04 23:56 UTC, IlmaMannix commented on src/resources/app/pages/UpdateTopic.vue
> +        // if (error) {
Delete this comment

2022-04-04 23:56 UTC, IlmaMannix commented on src/resources/app/pages/UpdateTopic.vue
> +      // topicDesc: "",
this too should be deleted

2022-04-04 23:56 UTC, IlmaMannix commented on src/resources/app/pages/UpdateTopic.vue
> +      <!-- <v-row>
This too should be deleted

2022-04-04 23:56 UTC, IlmaMannix commented on src/resources/app/pages/Classwork.vue
> +        location.reload();
this could be improved, but we can figure this out later 😅

2022-04-04 23:56 UTC, IlmaMannix commented on src/resources/app/pages/CreateTopic.vue
> +        <v-divider color="#06BBD3"></v-divider>
please use `<v-divider class="bg-primary"></v-divider>`

2022-04-04 23:56 UTC, IlmaMannix commented on src/resources/app/pages/CreateTopic.vue
> +      lengthRules: [(v) => (v.length <= 65535 || "Characters are off limit")],
should be `v.length <= 255`

2022-04-04 23:56 UTC, IlmaMannix commented on src/resources/app/pages/UpdateTopic.vue
> +      lengthRules: [(v) => (v.length <= 65535 || "Characters are off limit")],
this too should be `v.length <= 255`

2022-04-04 23:56 UTC, IlmaMannix commented on src/resources/app/pages/UpdateTopic.vue
> +        <v-divider color="#06BBD3"></v-divider>
please use `<v-divider class="bg-primary"></v-divider>`

2022-04-05 00:19 UTC, IlmaMannix approved these changes
good job Darren 👍👍

2022-04-05 00:21 UTC, AldiNFitrah approved these changes
Great job!

2022-04-05 00:22 UTC, merged